### ISSUE TITLE
Not working on Fedora 30

### ISSUE THREAD

**Issue by juhi24** [gufoe/text-translator#37]
I cannot get this to work on Fedora 30 / Gnome 3.32.2. I get the big fat ERROR label upon installation from extensions.gnome.org. 

I have translate-shell, clutter, clutter-gst3 and clutter-gtk installed. Am I missing some dependencies?

**Comment by armonge** [comment]
Hi @juhi24 could you please check if there's any more information? you can get into the latest logs for gnome extensions with the Looking Glass tool. To use it just type `Ctrl+r` and then `lg`

You could also try and search with the `gnome logs` application

**Comment by juhi24** [comment]
`text_translator_awamper.gmail.com has error: TypeError: this._construct is not a function`

**Comment by gufoe** [comment]
Any hint about the file/line?

**Comment by juhi24** [comment]
The interesting thing here is, I can't reproduce this anymore. It works!
