### ISSUE TITLE
No longer working with Gnome 3.32

### ISSUE THREAD

**Issue by armonge** [gufoe/text-translator#34]
I'm running archlinux with gnome 3.32, the extension won't load with this latest update. Looking at the errors from `lg` it shows

`this._contruct is not a function`

**Comment by armonge** [comment]
Apparently this is due to an update in the gnome-shell Javascript API

https://gitlab.gnome.org/GNOME/gjs/issues/233

**Comment by mnovozhylov** [comment]
same here, experiencing the same issue - it would be great to know if anyone is looking into this?

**Comment by marathone** [comment]
So, now that Gnome 3.32 is released, any chance this useful extension can be updated?

**Comment by mnovozhylov** [comment]
Gnome 3.32 is also a part of Ubuntu 19.04, so, the issue becomes critical for many users.

**Comment by gufoe** [comment]
I'm on Debian now and waiting for the release. I'm not too practical with the API (I did not write the extension, just mainaining it: pulling requests, try to fix some bugs).
I also am myself traveling and don't have too much time to download and install ubuntu.

**Comment by armonge** [comment]
@gufoe i sent a pull request which should fix the issues on gnome 3.32
