### ISSUE TITLE
3.34: this._init_most_used_bar is not a function

### ISSUE THREAD

**Issue by mokilcde** [gufoe/text-translator#40]
Hi!

After updating to Gnome to 3.34 the text-translator does not work

Error message:
gnome-shell[2821]: Extension "text_translator@awamper.gmail.com" had error: TypeError: this._init_most_used_bar is not a function

CU
  Michael

**Comment by mnovozhylov** [comment]
I'm getting
```
Jul 03 17:00:40 up gnome-shell[2871]: JS WARNING: [/home/..../.local/share/gnome-shell/extensions/text_translator@awamper.gmail.com/google_tts.js 9]: Too many arguments to function Gst.init: expected 1, got 2
Jul 03 17:00:40 up gnome-shell[2871]: Extension "text_translator@awamper.gmail.com" had error: TypeError: this._on_button_press is undefined
Jul 03 17:00:40 up gnome-software[3962]: text_translator_awamper.gmail.com has error: TypeError: this._on_button_press is undefined
Jul 03 17:00:40 up org.gnome.Shell.desktop[2871]: Window manager warning: Trying to remove non-existent keybinding "open-translator-dialog-keybinding".
Jul 03 17:00:40 up org.gnome.Shell.desktop[2871]: Window manager warning: Trying to remove non-existent keybinding "translate-from-clipboard-keybinding".
Jul 03 17:00:40 up org.gnome.Shell.desktop[2871]: Window manager warning: Trying to remove non-existent keybinding "translate-from-selection-keybinding".
```
and extension doesn't start

**Comment by gufoe** [comment]
Should be fixed now
